### ISSUE TITLE
Display time

### ISSUE THREAD

**Issue by Spiridusu** [sigvaldm/SevenSeg#8]
Hello. I will like to display time (in hours and minutes) on a display but I cant figure out how the code should look. I have managed to display number on it, using the code below, but I have problems displaying time. 

Can you please give me an example for how the code should look for displaying time?

```
#include <SevenSeg.h>
SevenSeg disp(6,7,8,9,10,11,12);
const int numOfDigits=4;
int digitPins[numOfDigits]={2,3,4,5};
void setup() {
  disp.setDigitPins(numOfDigits, digitPins);
  disp.setCommonCathode();
}  
void loop() {
    disp.write(1111);
}
```

**Comment by sigvaldm** [comment]
See the attached user guide, pages 11 and 12.
