### ISSUE TITLE
Doesn't work for single display  C-561H

### ISSUE THREAD

**Issue by fpilee** [sigvaldm/SevenSeg#9]
I tried on a Common Cathode single display and didn't worked :D 
```c
#include <SevenSeg.h>

SevenSeg disp (0,1,2,3,4,5,6) ;

void setup () {
  disp.setCommonCathode();
}
void loop () {
  disp.write(5) ;
}
```

**Comment by fpilee** [comment]
disp.writeDigit(5) ;

**Comment by 5ft24dave** [comment]
The command is disp.write(1358)
No spaces

⁣Sent from BlueMail ​

**Comment by fpilee** [comment]
Yes. But it doesn't work for only one display. I had to use writeDigit instead
